apiVersion: v1
kind: Service
metadata:
  name: pipi-mysql
  labels:
    app: pipi
spec:
  ports:
    - port: 3306
  selector:
    app: pipi
    tier: mysql
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pipi-mysql
  labels:
    app: pipi
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pipi
        tier: mysql
    spec:
      containers:
      - image: hypriot/rpi-mysql
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: "314159265359"
        - name: MYSQL_DATABASE
          value: "pipi_production"
        - name: MYSQL_USER
          value: "pipi"
        - name: MYSQL_PASSWORD
          value: "ilikepi"
        ports:
        - containerPort: 3306
          name: mysql